# Generated by Django 3.2.9 on 2022-02-08 21:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(default=home.models.id_gen, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=30)),
                ('genus', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=home.models.get_animal_image_path)),
            ],
        ),
    ]
